version: '3'

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
                  gateway: ${GATEWAY}

services:

    postgres:
        container_name: db-genin
        image: postgres:15.3-alpine
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
        volumes:
            - db-data:/var/lib/postgresql/data
            - db-logs:/logs
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        networks:
            - network
        restart: always

    api:
        container_name: api-genin
        build: 
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            PORT: ${PORT}
        ports:
            - "${PORT}:${PORT}"
        networks:
            - network
        restart: always

volumes:
    db-data:
    db-logs: